-- Raw database
CREATE DATABASE IF NOT EXISTS AMAZON_REVIEWS_RAW_DB;

CREATE SCHEMA IF NOT EXISTS AMAZON_REVIEWS_RAW_DB.RAW;

-- Dev/transform database
CREATE DATABASE IF NOT EXISTS AMAZON_REVIEWS_DEV_DB;

CREATE SCHEMA IF NOT EXISTS AMAZON_REVIEWS_DEV_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS AMAZON_REVIEWS_DEV_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS AMAZON_REVIEWS_DEV_DB.GOLD;