-- Create roles
CREATE ROLE IF NOT EXISTS DBT_ROLE;
CREATE ROLE IF NOT EXISTS REPORTER_ROLE;

-- Grant role hierarchy
GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;
GRANT ROLE REPORTER_ROLE TO ROLE SYSADMIN;

-- Grant to your login user
GRANT ROLE DBT_ROLE TO USER <YOUR_USERNAME>;
GRANT ROLE REPORTER_ROLE TO USER <YOUR_USERNAME>;