-- DBT_ROLE on RAW database (read + write for ingestion)
GRANT USAGE ON DATABASE AMAZON_REVIEWS_RAW_DB TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA AMAZON_REVIEWS_RAW_DB.RAW TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA AMAZON_REVIEWS_RAW_DB.RAW TO ROLE DBT_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA AMAZON_REVIEWS_RAW_DB.RAW TO ROLE DBT_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA AMAZON_REVIEWS_RAW_DB.RAW TO ROLE DBT_ROLE;

-- DBT_ROLE on DEV database (full control for transformations)
GRANT USAGE ON DATABASE AMAZON_REVIEWS_DEV_DB TO ROLE DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA AMAZON_REVIEWS_DEV_DB.BRONZE TO ROLE DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA AMAZON_REVIEWS_DEV_DB.SILVER TO ROLE DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA AMAZON_REVIEWS_DEV_DB.GOLD TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AMAZON_REVIEWS_DEV_DB.BRONZE TO ROLE REPORTER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AMAZON_REVIEWS_DEV_DB.SILVER TO ROLE REPORTER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AMAZON_REVIEWS_DEV_DB.GOLD TO ROLE REPORTER_ROLE;

-- REPORTER_ROLE on DEV database (read only)
GRANT USAGE ON DATABASE AMAZON_REVIEWS_DEV_DB TO ROLE REPORTER_ROLE;
GRANT USAGE ON SCHEMA AMAZON_REVIEWS_DEV_DB.BRONZE TO ROLE REPORTER_ROLE;
GRANT USAGE ON SCHEMA AMAZON_REVIEWS_DEV_DB.SILVER TO ROLE REPORTER_ROLE;
GRANT USAGE ON SCHEMA AMAZON_REVIEWS_DEV_DB.GOLD TO ROLE REPORTER_ROLE;