name: dbt CI Pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '03-amazon-reviews-project/amazon_reviews_dbt/**'
  pull_request:
    branches:
      - main
    paths:
      - '03-amazon-reviews-project/amazon_reviews_dbt/**'

jobs:
  dbt-ci:
    name: Run dbt build and tests
    runs-on: ubuntu-latest

    env:
      DBT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_P3 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          amazon_reviews_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT_P3 }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD_P3 }}
                role: DBT_ROLE
                warehouse: TRANSFORM_WH
                database: AMAZON_REVIEWS_DEV_DB
                schema: BRONZE
                threads: 4
          EOF

      - name: dbt debug
        working-directory: 03-amazon-reviews-project/amazon_reviews_dbt
        run: dbt debug

      - name: dbt build
        working-directory: 03-amazon-reviews-project/amazon_reviews_dbt
        run: dbt build